### ISSUE TITLE
feat(*): migrate from node 14 to 16

### ISSUE THREAD

**Issue by pr-Mais** [firebase/extensions#1564]
All extensions will be migrated from using node 14 to 16, this issue will track these updates.

### Migration list

- [x] [auth-mailchimp-sync](https://github.com/firebase/extensions/tree/next/auth-mailchimp-sync) #1570 
- [x] [delete-user-data](https://github.com/firebase/extensions/tree/next/delete-user-data) #1566 
- [x] [firestore-bigquery-export](https://github.com/firebase/extensions/tree/next/firestore-bigquery-export) #1571 
- [x] [firestore-counter](https://github.com/firebase/extensions/tree/next/firestore-counter) #1573 
- [x] [firestore-send-email](https://github.com/firebase/extensions/tree/next/firestore-send-email) #1574 
- [x] [firestore-shorten-urls-bitly](https://github.com/firebase/extensions/tree/next/firestore-shorten-urls-bitly) #1574 
- [x] [firestore-translate-text](https://github.com/firebase/extensions/tree/next/firestore-translate-text) #1574 
- [x] [rtdb-limit-child-nodes](https://github.com/firebase/extensions/tree/next/rtdb-limit-child-nodes) #1574 
- [x] [storage-resize-images](https://github.com/firebase/extensions/tree/next/storage-resize-images) #1574
