### ISSUE TITLE
feat(*): migrate from node 16 to 18

### ISSUE THREAD

**Issue by dackers86** [firebase/extensions#1590]
All extensions will be migrated from using node 16 to 18 this issue will track these updates.

### Migration list

- [x] [auth-mailchimp-sync](https://github.com/firebase/extensions/tree/next/auth-mailchimp-sync) #1599
- [x] [delete-user-data](https://github.com/firebase/extensions/tree/next/delete-user-data) #1595
- [x] [firestore-bigquery-export](https://github.com/firebase/extensions/tree/next/firestore-bigquery-export) #1596
- [x] [firestore-counter](https://github.com/firebase/extensions/tree/next/firestore-counter) #1591  
- [x] [firestore-send-email](https://github.com/firebase/extensions/tree/next/firestore-send-email) #1593
- [x] [firestore-shorten-urls-bitly](https://github.com/firebase/extensions/tree/next/firestore-shorten-urls-bitly) #1592
- [x] [firestore-translate-text](https://github.com/firebase/extensions/tree/next/firestore-translate-text) #1594
- [x] [rtdb-limit-child-nodes](https://github.com/firebase/extensions/tree/next/rtdb-limit-child-nodes) #1598
- [x] [storage-resize-images](https://github.com/firebase/extensions/tree/next/storage-resize-images) #1597
- [x] [samples](https://github.com/firebase/extensions/tree/next/samples) #1600
- [x] [project]](https://github.com/firebase/extensions/tree/next/samples) #1601
